version: "3.9"
services:
  web:
    image: ghcr.io/mts-gaming/rust:latest
    ports:
      - "28015:28015/udp"
      - "28015:28015/tcp"
      - "28016:28016/tcp"
    environment:
      - PORT: 28015
      - RCON_PORT: 28016
      - RCON_WEB: 1
      - RCON_PASS: password
      - SERVERNAME: My Rust Server
      - SEED: 12345
      - TICK: 10
      - SAVEINT: 600
      - MAXPLAYERS: 10
      - WORLDSIZE: 4000
    volumes:
      - rust:/rust/server
